### ISSUE TITLE
Incorrect value returned from NSession::HasExpired

### ISSUE THREAD

**Issue by JoshR604** [heroiclabs/nakama-cocos2d-x#10]
From the server documentation (and the wording of the function) it seems that HasExpired should return true when ‘time’ is greater than or equal to ‘expiresAt’.

Currently it returns true if time is less than or equal to expiresAt in both cocos2dx & unreal SDKs:

bool NSession::HasExpired(milliseconds time)
	{
		return time <= expiresAt;
	}

Whereas the js and .net SDKs are consistent with the documentation: 

isexpired(currenttime: number): boolean {
    return (this.expires_at - currenttime) < 0;
  }

public bool HasExpired(DateTime dateTime)
        {
            var expireDatetime = Epoch + TimeSpan.FromSeconds(ExpireTime);
            return dateTime > expireDatetime;
        }

**Comment by Dimon4eg** [comment]
Sorry for late reply and thank you for reporting the bug.
It's already fixed in 2.x branch.
It will be released soon.
