### ISSUE TITLE
Upgrade to Nakama 2.

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-cocos2d-x#11]
Currently the client is compatible with Nakama 1.4.x. We should update the client to use Nakama 2 and use [Nakama C++ Client](https://github.com/heroiclabs/nakama-cpp) as much as possible to minimise code duplication. 

The client should work on Desktop, iOS, Android and as many other target outputs as possible. This client library is the sibling library to [Nakama Cocos2d-x Javascript](https://github.com/heroiclabs/nakama-cocos2d-x-javascript) (which is already compatible with Nakama 2).

**Comment by mofirouz** [comment]
Also make sure that SSL is fully supported.

**Comment by Dimon4eg** [comment]
Upgrade to Nakama 2 done.
For SSL there is dedicated issue.
