### ISSUE TITLE
Add client guide.

### ISSUE THREAD

**Issue by mofirouz** [heroiclabs/nakama-cocos2d-x#12]
This work needs to be submitted against the [nakama-docs](https://github.com/heroiclabs/nakama-docs) repository so we can publish it directly on the website.

Follow this guide format: https://github.com/heroiclabs/nakama-docs/blob/master/docs/android-java-client-guide.md

This should be considered separate additional documentation to Cocos2d-x JS docs.

**Comment by Dimon4eg** [comment]
Done.
