### ISSUE TITLE
Send INUncollatedMessage

### ISSUE THREAD

**Issue by JoshR604** [heroiclabs/nakama-cocos2d-x#8]
I am unable to send a NMatchDataSendMessage in the cocos2dx SDK, looking at the Unreal SDK it seems there is a missing function in NClient:
 
`void NClient::Send(INUncollatedMessage& message, std::function<void(NError)> errback)`

I can't find any other way to send an 'INUncollatedMessage' message..

**Comment by novabyte** [comment]
Thanks @JoshR604 nice catch! Would you be able to open a pull request with the change?

**Comment by JoshR604** [comment]
@novabyte for sure, I will try to get a PR up asap 👍
